// wp-content/themes/Tailbase/resources/assets/js/components/VideoPlayer.tsx
import React, { useRef, useState, useEffect } from 'react';
import styled from 'styled-components';


const Video = styled.video`
    @media (min-width: 1024px) {
        width: 900px;
    }
`;


export default function VideoPlayer(props: {
    type: string;
    src: string;
    className?: string;
}) {
    const {
        type,
        src,
        className = ''
    } = props;

    const ref = useRef(null);

    const [fullscreenSupported, setFullscreenSupported] = useState(true);

    useEffect(() => {
        // @ts-ignore
        setFullscreenSupported(document.fullscreenEnabled || document.mozFullscreenEnabled || document.webkitFullscreenEnabled || document.msFullscreenEnabled)
    }, []);

    return (!type || !src) ? null : (
        <div className={className ?? ''}>
            <Video
                ref={ref}
                muted
            >
                <source
                    type={type}
                    src={src}
                />
            </Video>

            <div className="flex justify-end mt-1">
                <a
                    href="#"
                    onClick={e => {
                        e.preventDefault();
                        ref.current.muted = false;
                        ref.current.play();
                    }}
                >
                    play
                </a>
                <a
                    href="#"
                    onClick={e => {
                        e.preventDefault();
                        ref.current.pause();
                        ref.current.muted = true;
                    }}
                    className="ml-4"
                >
                    pause
                </a>
                {fullscreenSupported && (
                    <a
                        href="#"
                        onClick={e => {
                            e.preventDefault();
                            ref.current.requestFullscreen();
                        }}
                        className="ml-4"
                    >
                        fullscreen
                    </a>
                )}
            </div>
        </div>
    )
}

// wp-content/themes/Tailbase/resources/assets/js/components/video-player.vue
<template>
    <div class="mx-4">
        <video
            ref="video"
            muted
        >
            <source :type="type" :src="src"/>
        </video>
        <div class="flex justify-end mt-1">
            <a
                href="#"
                @click.prevent="play"
                class="mr-4"
            >
                play
            </a>
            <a
                href="#"
                @click.prevent="pause"
                class="mr-4"
            >
                pause
            </a>
            <a
                v-if="fullscreenSupported"
                href="#"
                @click.prevent="fullscreen"
            >
                fullscreen
            </a>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        type: {
            type: String,
            required: true,
        },
        src: {
            type: String,
            required: true
        }
    },

    mounted: function () {
        this.fullscreenSupported = document.fullscreenEnabled || document.mozFullscreenEnabled || document.webkitFullscreenEnabled || document.msFullscreenEnabled;
    },

    data: function () {
        return {
            fullscreenSupported: true
        };
    },

    methods: {
        play: function () {
            this.$refs.video.muted = false;
            this.$refs.video.play();
        },

        pause: function () {
            this.$refs.video.pause();
            this.$refs.video.muted = true;
        },

        fullscreen: function () {
            this.$refs.video.requestFullscreen();
        }
    }
}
</script>

<style lang="scss" scoped>
video {
    @media (min-width: 1024px) {
        width: 900px;
    }
}
</style>
