// wp-content/themes/Tailbase/resources/assets/js/components/VideosIndex.tsx
import React, { useEffect, useRef, useState } from 'react';
import styled from 'styled-components';
import { useQuery, PostObjectsConnectionOrderbyEnum, OrderEnum, VideoProject_Videoattributes_videos } from '../gqty';


const Video = styled.video<{
    show: boolean;
}>`
    width: 1000px;
    max-width: 80%;
    max-height: 90%;
    position: absolute;
    z-index: 1;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    transition: opacity .4s;
    opacity: ${props => props.show ? 1 : 0};
`;


const Link = styled.a`
    z-index: 10;
    &.selected {
        h2 {
            color: #ccf4f9;
        }
    }

    &.not-selected {
        h2 {
            opacity: 0;
        }
    }

    h2 {
        font-size: 45px;
        max-width: 900px;
        text-align: center;
        opacity: 1;
        transition: opacity .4s, color .1s;
    }
`;


const Title = styled.h2`
    font-size: 45px;
    max-width: 900px;
    text-align: center;
    opacity: 1;
    transition: opacity .4s, color .1s;
`;


export default function VideosIndex() {
    const projects = useQuery().videoProjects({
        where: {
            orderby: [
                {
                    field: PostObjectsConnectionOrderbyEnum.MENU_ORDER,
                    order: OrderEnum.ASC
                }
            ]
        }
    }).nodes;

    const videoRef = useRef(null);

    const [selected, setSelected] = useState(null);
    const [selectedVideo, setSelectedVideo] = useState<VideoProject_Videoattributes_videos | null>(null);
    
    useEffect(() => {
        if (window.innerWidth < 1024) {
            setSelectedVideo(null);
            return;
        }

        const videos = projects?.find(p => p.id === selected)?.videoAttributes?.videos ?? [];
        const randomIndex = Math.floor((Math.random()) * ((videos.length - 1) + 1));
        setSelectedVideo(videos[randomIndex] ?? null);
    }, [selected]);

    useEffect(() => {
        if (selectedVideo && selectedVideo.file.mediaItemUrl) {
            videoRef.current.currentTime = 0;
            videoRef.current.muted = false;
            videoRef.current.play();
        } else {
            videoRef.current.pause();
            videoRef.current.muted = true;
        }
    }, [selectedVideo]);

    return (
        <>
            <Video
                ref={videoRef}
                show={!!selected}
                muted
            >
                {!!selectedVideo && (
                    <source
                        type={selectedVideo.file.mimeType}
                        src={selectedVideo.file.mediaItemUrl}
                    />
                )}
            </Video>

            <div className="w-full h-full flex flex-col justify-center items-center mx-4">
                {projects?.map((p, index) => (
                    <Link
                        key={index}
                        href={p.link}
                        className={`flex mb-16 lg:mb-0 ${selected === p.id ? 'selected' : ''} ${!!selected && selected !== p.id ? 'not-selected' : ''}`}
                        onMouseEnter={() => setSelected(p.id)}
                        onMouseLeave={() => setSelected(null)}
                    >
                        <Title>
                            {p.title()}
                        </Title>
                    </Link>
                ))}
            </div>
        </>
    );
}

// wp-content/themes/Tailbase/resources/assets/js/components/videos-index.vue
<template>
    <div class="w-full h-full flex justify-between pt-4 pb-24">
        <video
            ref="video"
            :class="{ show: !!selected }"
            muted
        >
            <source
                v-if="selectedVideo"
                :type="selectedVideo.type"
                :src="selectedVideo.src"
            />
        </video>

        <div class="w-full h-full flex flex-col justify-center items-center mx-4">
            <a
                v-for="(project, index) in projects"
                :key="index"
                :href="project.link"
                :class="[
                    'flex mb-16 lg:mb-0',
                    {
                        selected: selected === project.id,
                        'not-selected': !!selected && selected !== project.id
                    }
                ]"
                @mouseenter="selected = project.id"
                @mouseleave="selected = null"
            >
                <h2 class="text-ocean">
                    {{ project.title }}
                </h2>
            </a>
        </div>
    </div>
</template>

<script>
import { validateJSON } from '../helpers';


export default {
    props: {
		itemsStr: {
			type: String,
			required: true,
			validator: validateJSON
		}
    },

    data: function () {
        return {
            selected: null,
            image: null
        };
    },

    watch: {
        selectedVideo: function (video) {
            console.log(video);
            if (video && video.src) {
                this.$refs.video.currentTime = 0;
                this.$refs.video.muted = false;
                this.$refs.video.play();
            } else {
                this.$refs.video.pause();
                this.$refs.video.muted = true;
            }
        }
    },

    computed: {
		projects: function () {
			return JSON.parse(this.itemsStr);
		},

        selectedVideo: function () {
            if (window.innerWidth < 1024) {
                return null;
            }

            const videos = (this.projects.find(v => v.id === this.selected) || { videos: [] }).videos;
            const randomIndex = Math.floor((Math.random()) * ((videos.length - 1) + 1));
            return videos[randomIndex] || null;
        }
    }
}
</script>

<style lang="scss" scoped>
video {
    width: 1000px;
    max-width: 80%;
    max-height: 90%;
    position: absolute;
    z-index: 1;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    opacity: 0;
    transition: opacity .4s;
    &.show {
        opacity: 1;
    }
}

a {
    z-index: 10;
    &.selected {
        h2 {
            color: #ccf4f9;
        }
    }

    &.not-selected {
        h2 {
            opacity: 0;
        }
    }

    h2 {
        font-size: 45px;
        max-width: 900px;
        text-align: center;
        opacity: 1;
        transition: opacity .4s, color .1s;
    }
}

h2 {
    font-size: 45px;
    text-align: center;
}
</style>
